import { removeFirstAndLast } from './functions.js';
import { isReversible } from './functions.js';
import { countVowels } from './functions.js';
import { isPangram } from './functions.js';
import { hasAllVowels } from './functions.js';
import { countdown } from './functions.js';
import { getUserAge } from './functions.js';
import { isAdult } from './functions.js';
import { castADice } from './functions.js';
import { isLeapYear } from './functions.js';
import { playGame } from './functions.js';
import { getRandomUserData } from './functions.js';
import { getTip } from './functions.js';
import { getDiscount } from './functions.js';

console.log(removeFirstAndLast('murcielago'));
console.log(isReversible('osttso'));
console.log(countVowels('murcielago'));
console.log(isPangram('Lorem Ipsum'));
console.log(hasAllVowels('Lorem Ipsum'));
console.log(countdown(5));
console.log(getUserAge(1978));
console.log(isAdult(21));
console.log('Tirada aleatoria 1: ', castADice());
console.log('Tirada aleatoria 1: ', castADice());
console.log('Tirada aleatoria 1: ', castADice());
console.log(isLeapYear(2020));
console.log(isLeapYear(2021));
console.log(isLeapYear(2022));
console.log(isLeapYear(2023));
console.log(isLeapYear(2024));
playGame();
console.log(getRandomUserData());
getTip(120, 16);
getDiscount(100, 16);
